<?xml version="1.0" encoding="utf-8"?><Database Name="CG" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSI\SQLEXPRESS;Initial Catalog=CG;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="WindowsFormsApp1.Properties.Settings" SettingsPropertyName="CGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId1">
      <Argument Parameter="name" Member="Name" />
      <Argument Parameter="department" Member="Department" />
      <Argument Parameter="salary" Member="Salary" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId2">
      <Argument Parameter="id" Member="Id" />
      <Argument Parameter="name" Member="Name" />
      <Argument Parameter="department" Member="Department" />
      <Argument Parameter="salary" Member="Salary" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId3">
      <Argument Parameter="id" Member="Id" />
    </DeleteFunction>
  </Table>
  <Function Id="FunctionId3" Name="dbo.sp_DeleteEmployee" Method="sp_DeleteEmployee">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_GetEmployeeById" Method="sp_GetEmployeeById">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_GetEmployeeByIdResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetEmployees" Method="sp_GetEmployees">
    <ElementType Name="sp_GetEmployeesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Id="FunctionId1" Name="dbo.sp_InsertEmployee" Method="sp_InsertEmployee">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Department" Parameter="department" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Salary" Parameter="salary" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId2" Name="dbo.sp_UpdateEmployee" Method="sp_UpdateEmployee">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Department" Parameter="department" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Salary" Parameter="salary" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Return Type="System.Int32" />
  </Function>
</Database>